import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
} from "react-icons/ai";
import { SiUpwork } from "react-icons/si";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import dief from "../public/صورة واتساب بتاريخ 2024-03-26 في 22.10.41_06982e65.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import proj1 from "../public/PowerBI projects/1.jpg";
import proj2 from "../public/PowerBI projects/2.jpg";
import proj3 from "../public/PowerBI projects/3.jpg";
import proj4 from "../public/PowerBI projects/4.jpg";
import proj5 from "../public/PowerBI projects/5.jpg";
import proj6 from "../public/PowerBI projects/6.jpg";
import proj7 from "../public/PowerBI projects/7.jpg";
import proj8 from "../public/PowerBI projects/8.jpg";
import proj9 from "../public/PowerBI projects/9.jpg";
import proj10 from "../public/PowerBI projects/10.jpg";
import proj11 from "../public/PowerBI projects/11.jpg";
import dashboard from "../public/dashboard.png";
import database1 from "../public/DatabaseProjects/1.jpg";
import database2 from "../public/DatabaseProjects/2.jpg";
import database3 from "../public/DatabaseProjects/3.jpg";
import novypro from "../public/novyPro Logo a PowerBI portfolio builder-381556704.png";
export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Dief Mohamed Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/dief.jpg" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Dief Mohamed</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1UkmIzk6hCxGBYmIUgC1mfWNMU_vaBw0N/view"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Dief Mohamed
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl w-[450px] mx-auto">
              Power BI Developer, Database Developer & Administrator.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for database development and
              adminstration and build power bi dashboards . Join me down below
              and let&apos;s get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://github.com/Diefmohamed210">
                <AiFillGithub />
              </a>
              <a href="https://www.linkedin.com/in/dief-mohamed2020/">
                <AiFillLinkedin />
              </a>

              <a href="https://www.upwork.com/freelancers/~017d19c5d7667b6bdc">
                <SiUpwork />
              </a>
              <a href="https://www.novypro.com/profile_projects/member----4339">
                <Image
                  src={novypro}
                  alt=""
                  height={40}
                  width={40}
                  rounded-full
                />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={dief} layout="fill" objectFit="cover" alt="" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance Power BI
              Developer, Database Developer & Administrator, I&apos;ve done
              remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including brand design,
              programming and teaching.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={dashboard} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Beautiful Dashboards
              </h3>
              <p className="py-2">
                Creating and designing dashboard and reports
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Power BI</p>
              <p className="text-gray-800 py-1">Excel</p>
              <p className="text-gray-800 py-1">Tabluea</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code your dream project
              </h3>
              <p className="py-2">
                Do you have an idea for your next great project? Let&apos;s make
                it a reality.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Power BI</p>
              <p className="text-gray-800 py-1">Excel</p>
              <p className="text-gray-800 py-1">Tabluea</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} alt="" />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting</h3>
              <p className="py-2">
                Are you interested in feedback for your current project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1 block">
                diefmohamed2021@gmail.com
              </p>

              <p className="text-gray-800 py-1 block">
                Whatsapp 002 01121057120
              </p>
              <a
                href="https://www.linkedin.com/in/dief-mohamed2020/"
                className="text-gray-800 py-1 block text-teal-700 hover:text-blue-500"
              >
                Linkedin
              </a>
            </div>
          </div>
        </section>

        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Since the beginning of my journey as a freelance Power BI
              Developer, Database Developer & Administrator, I&apos;ve done
              remote work for
              <span className="text-teal-500"> agencies </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talanted people to create digital products
              for both business and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer from a wide range of services, including dashboard design,
              database adminstration.
            </p>
          </div>
          <h1 className="text-2xl text-center my-10 bg-teal-100 text-teal-700 w-96 rounded p-2 mx-auto">
            Dashboard Projects
          </h1>
          <div className="flex flex-col gap-5  lg:flex-row lg:flex-wrap  rounded-lg shadow-lg">
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/dashboard-68">
                <Image
                  className="rounded-lg object-cotain "
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj1}
                  alt=""
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/pizza-dashboard-">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj2}
                  alt=""
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/dashboard-51">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj3}
                  alt=""
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/sales-analysis-70">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj4}
                  alt=""
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/kpi-visuals-tip">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj5}
                  alt=""
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/dashboard-41">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj6}
                  alt=""
                />
              </a>
            </div>

            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/top-100-youtuber-dashboard">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj8}
                  alt=""
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/call-center-dashboard-7">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj9}
                  alt=""
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/dashboard--1">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj10}
                  alt=""
                />
              </a>
            </div>

            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/chrismas-sales-dashboard">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj7}
                  alt=""
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <a href="https://www.novypro.com/project/diversity-inclusion-dashboard-">
                <Image
                  className="rounded-lg object-cotain"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={proj11}
                  alt=""
                />
              </a>
            </div>
          </div>

          <h1 className="text-2xl text-center my-10 bg-teal-100 text-teal-700 w-96 rounded p-2 mx-auto">
            Database Projects
          </h1>
          <div className="flex flex-row gap-5 lg:flex-row lg:flex-wrap rounded-lg shadow-lg">
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <Image
                className="rounded-lg object-cotain "
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={database1}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <Image
                className="rounded-lg object-cotain"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={database2}
                alt=""
              />
            </div>
            <div className="basis-1/3 flex-1 hover:border-2 hover:border-white-700 rounded-lg shadow-md shadow-gray-600">
              <Image
                className="rounded-lg object-cotain"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={database3}
                alt=""
              />
            </div>
          </div>
          <a href="https://github.com/Diefmohamed210/ITI_Graduation_Progect_BI_Developer_Track/tree/main">
            <h1 className="text-2xl text-center my-10 bg-teal-100 text-teal-700 w-96 rounded p-2 mx-auto">
              See More Projects
            </h1>
          </a>
        </section>
      </main>
    </div>
  );
}
